Splitting main.sh in bsbp and script.template

diff --git a/bsbp b/bsbp
--- a/bsbp
+++ b/bsbp
@@ -13,6 +13,7 @@
 #
 # Authors:
 #  - Kevin van Zonneveld (http://kvz.io)
+#  - Matteo Sasso (matteo.sasso@gmail.com)
 #
 # Usage:
 #  LOG_LEVEL=7 ./main.sh -f /tmp/x -d
@@ -21,28 +22,34 @@
 # Copyright (c) 2013 Kevin van Zonneveld (http://kvz.io)
 
 
-### Configuration
+
+### Runtime
 #####################################################################
 
-# Environment variables and their defaults
-LOG_LEVEL="${LOG_LEVEL:-6}" # 7 = debug -> 0 = emergency
+# Exit on error. Append '|| true' or '|| :' if you expect an error.
+# set -e is safer than #!/bin/bash -e because that is neutralised if
+# someone runs your script like `bash yourscript.sh`
+set -o errexit
+set -o nounset
 
-# Commandline options. This defines the usage page, and is used to parse cli
-# opts & defaults from. The parsing is unforgiving so be precise in your syntax
-read -r -d '' usage <<-'EOF'
-  -f   [arg] Filename to process. Required.
-  -t   [arg] Location of tempfile. Default="/tmp/bar"
-  -d         Enables debug mode
-  -h         This page
-EOF
+# Bash will remember & return the highest exitcode in a chain of pipes.
+# This way you can catch the error in case mysqldump fails in `mysqldump |gzip`
+set -o pipefail
 
-# Set magic variables for current FILE & DIR
-__dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
-__file="${__dir}/$(basename "${BASH_SOURCE[0]}")"
+shopt -s nullglob
+shopt -s extglob
+shopt -s globstar
+shopt -u sourcepath
+
+trap _cleanup EXIT
 
 
 ### Functions
 #####################################################################
+
+function _cleanup () {
+  [[ "$(type -t cleanup)" == function ]] && cleanup
+}
 
 function _fmt ()      {
   local color_ok="\x1b[32m"
@@ -60,14 +67,32 @@ function _fmt ()      {
   fi
   echo -e "$(date -u +"%Y-%m-%d %H:%M:%S UTC") ${color}$(printf "[%9s]" ${1})${color_reset}";
 }
+
+# A "panic" condition usually affecting multiple apps/servers/sites. At this level it would usually notify all tech staff on call.
 function emergency () {                             echo "$(_fmt emergency) ${@}" 1>&2 || true; exit 1; }
+
+# Should be corrected immediately, therefore notify staff who can fix the problem. An example would be the loss of a primary ISP connection.
 function alert ()     { [ "${LOG_LEVEL}" -ge 1 ] && echo "$(_fmt alert) ${@}" 1>&2 || true; }
+
+# Should be corrected immediately, but indicates failure in a primary system, an example is a loss of a backup ISP connection.
 function critical ()  { [ "${LOG_LEVEL}" -ge 2 ] && echo "$(_fmt critical) ${@}" 1>&2 || true; }
+
+# Non-urgent failures, these should be relayed to developers or admins; each item must be resolved within a given time.
 function error ()     { [ "${LOG_LEVEL}" -ge 3 ] && echo "$(_fmt error) ${@}" 1>&2 || true; }
+
+# Warning messages, not an error, but indication that an error will occur if action is not taken, e.g. file system 85% full - each item must be resolved within a given time. This is a debug message
 function warning ()   { [ "${LOG_LEVEL}" -ge 4 ] && echo "$(_fmt warning) ${@}" 1>&2 || true; }
+
+# Events that are unusual but not error conditions - might be summarized in an email to developers or admins to spot potential problems - no immediate action required.
 function notice ()    { [ "${LOG_LEVEL}" -ge 5 ] && echo "$(_fmt notice) ${@}" 1>&2 || true; }
+
+# Normal operational messages - may be harvested for reporting, measuring throughput, etc. - no action required.
 function info ()      { [ "${LOG_LEVEL}" -ge 6 ] && echo "$(_fmt info) ${@}" 1>&2 || true; }
+
+# Info useful to developers for debugging the application, not useful during operations.
 function debug ()     { [ "${LOG_LEVEL}" -ge 7 ] && echo "$(_fmt debug) ${@}" 1>&2 || true; }
+
+
 
 function help () {
   echo "" 1>&2
@@ -78,10 +103,15 @@ function help () {
   exit 1
 }
 
-function cleanup_before_exit () {
-  info "Cleaning up. Done"
+function def() {
+  IFS='\n' read -r -d '' "$1" || :
 }
-trap cleanup_before_exit EXIT
+
+# Set magic variables for current FILE & DIR
+__dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
+__file="${__dir}/$(basename "${BASH_SOURCE[0]}")"
+
+
 
 
 ### Parse commandline options
@@ -105,14 +135,14 @@ while read line; do
     match="$(echo "${line}" |sed 's#^.*Default=\(\)#\1#g')"
     eval "${varname}=\"${match}\""
   fi
-done <<< "${usage}"
+done <<< "${arguments}"
 
 # Reset in case getopts has been used previously in the shell.
 OPTIND=1
 
 # Overwrite $arg_<flag> defaults with the actual CLI options
 while getopts "${opts}" opt; do
-  line="$(echo "${usage}" |grep "\-${opt}")"
+  line="$(echo "${arguments}" |grep "\-${opt}")"
 
 
   [ "${opt}" = "?" ] && help "Invalid use of script: ${@} "
@@ -148,36 +178,3 @@ if [ "${arg_h}" = "1" ]; then
   help "Help using ${0}"
 fi
 
-
-### Validation (decide what's required for running your script and error out)
-#####################################################################
-
-[ -z "${arg_f}" ]     && help      "Setting a filename with -f is required"
-[ -z "${LOG_LEVEL}" ] && emergency "Cannot continue without LOG_LEVEL. "
-
-
-### Runtime
-#####################################################################
-
-# Exit on error. Append ||true if you expect an error.
-# set -e is safer than #!/bin/bash -e because that is neutralised if
-# someone runs your script like `bash yourscript.sh`
-set -o errexit
-set -o nounset
-
-# Bash will remember & return the highest exitcode in a chain of pipes.
-# This way you can catch the error in case mysqldump fails in `mysqldump |gzip`
-set -o pipefail
-
-if [[ "${OSTYPE}" == "darwin"* ]]; then
-  info "You are on OSX"
-fi
-
-debug "Info useful to developers for debugging the application, not useful during operations."
-info "Normal operational messages - may be harvested for reporting, measuring throughput, etc. - no action required."
-notice "Events that are unusual but not error conditions - might be summarized in an email to developers or admins to spot potential problems - no immediate action required."
-warning "Warning messages, not an error, but indication that an error will occur if action is not taken, e.g. file system 85% full - each item must be resolved within a given time. This is a debug message"
-error "Non-urgent failures, these should be relayed to developers or admins; each item must be resolved within a given time."
-critical "Should be corrected immediately, but indicates failure in a primary system, an example is a loss of a backup ISP connection."
-alert "Should be corrected immediately, therefore notify staff who can fix the problem. An example would be the loss of a primary ISP connection."
-emergency "A \"panic\" condition usually affecting multiple apps/servers/sites. At this level it would usually notify all tech staff on call."
